require: rubocop-rails

AllCops:
  NewCops: enable
  DisplayCopNames: true
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'config.ru'
    - 'config/**/*'
    - 'db/**/*'
    - 'features/support/env.rb'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'Rakefile'
    - 'Guardfile'
    - 'script/**/*'
    - 'spec/factories/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: double_quotes
